spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library-management-system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  application:
    name: library-management-api
  sql:
    init:
      mode: always
      platform: postgres
      data-locations: classpath:data.sql