spring:
  datasource:
    url: ${JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: ${DEFER_DATASOURCE_INITIALIZATION:false}
  application:
    name: library-management-api
  sql:
    init:
      mode: ${SQL_INIT_MODE:never}
      platform: postgres
      data-locations: classpath:data.sql
